# Generated by Django 5.0.6 on 2024-05-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=6, max_length=2),
            preserve_default=False,
        ),
    ]
