# Generated by Django 5.0.6 on 2024-05-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_orderdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orderDetails',
            new_name='orderDetail',
        ),
    ]
