# Generated by Django 5.0.6 on 2024-05-28 17:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_rename_orderdetails_orderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('in_stock', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='sales.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
