# Generated by Django 5.0.6 on 2024-06-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default=1, upload_to='media/images'),
            preserve_default=False,
        ),
    ]
